### ISSUE TITLE
Glances Unknown option warning in system logs when starting Homeassistant.

### ISSUE THREAD

**Issue by SignalGroup** [hassio-addons/addon-glances#333] opened 2023-03-25 18:47 UTC
# Problem/Motivation

Receiving the following error when starting HomeAssistant in both my work and home environments:

23-03-25 14:40:51 INFO (SyncWorker_11) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/glances/amd64 with version 0.18.0
23-03-25 14:40:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'version' for Glances (a0d7b954_glances)
23-03-25 14:40:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'token' for Glances (a0d7b954_glances)
23-03-25 14:40:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'bucket' for Glances (a0d7b954_glances)
23-03-25 14:40:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'org' for Glances (a0d7b954_glances)

> (Why the issue was filed)
Wanted to fix the reported error.  To confirm that it is not just a visual warning with no action needed.

## Expected behavior

No error messages..

## Actual behavior

23-03-25 14:40:51 INFO (SyncWorker_11) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/glances/amd64 with version 0.18.0
23-03-25 14:40:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'version' for Glances (a0d7b954_glances)
23-03-25 14:40:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'token' for Glances (a0d7b954_glances)
23-03-25 14:40:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'bucket' for Glances (a0d7b954_glances)
23-03-25 14:40:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'org' for Glances (a0d7b954_glances)

## Steps to reproduce

Start homeassistant.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

I have tried uninstalling, rebooting and reinstalling.  Error still occurs.  

I am on the latest version of Homeassistant and glances.

**Comment by sinclairpaul** [comment] 2023-03-25 18:58
Duplicate of #328

**Closed by sinclairpaul** 2023-03-25 18:58 UTC

**Comment by SignalGroup** [comment] 2023-03-27 11:24
Sorry for the duplicate request.  Not sure how I missed that, I did actually search.

Thanks
Dave
