### ISSUE TITLE
no data export glances to influx

### ISSUE THREAD

**Issue by mariuszxeno** [hassio-addons/addon-glances#334] opened 2023-03-26 11:02 UTC
Problem/Motivation

Add-on config:

```log_level: info
process_info: false
refresh_time: 10
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
influxdb:
  enabled: true
  host: a0d7b954-influxdb
  port: 8086
  interval: 10
  ssl: false
  version: 1
  username: xxxxx
  password: xxxxx
  database: glances
  prefix: localhost
  token: ""
  bucket: glances
  org: myorg
```
Log:
```-----------------------------------------------------------
 Add-on: Glances
 A cross-platform system monitoring tool
-----------------------------------------------------------
 Add-on version: 0.18.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.3.6
 Home Assistant Supervisor: 2023.03.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
INFO: Starting Glances...
Glances Web User Interface started on http://127.0.0.1:61209/
INFO: Starting NGinx...
Traceback (most recent call last):
  File "/usr/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 179, in main
    start(config=core.get_config(), args=core.get_args())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/standalone.py", line 45, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 39, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 90, in load_modules
    self.load_exports(args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 167, in load_exports
    self._exports[export_name] = export_module.Export(args=args, config=self.config)
  File "/usr/lib/python3.10/site-packages/glances/exports/glances_influxdb.py", line 51, in __init__
    self.client = self.init()
  File "/usr/lib/python3.10/site-packages/glances/exports/glances_influxdb.py", line 65, in init
    db = InfluxDBClient(
  File "/usr/lib/python3.10/site-packages/influxdb/client.py", line 115, in __init__
    self.__port = int(port)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```
Supervisor log:
```23-03-26 12:03:07 WARNING (MainThread) [supervisor.addons.options] Unknown option 'version' for Glances (a0d7b954_glances)
23-03-26 12:03:07 WARNING (MainThread) [supervisor.addons.options] Unknown option 'token' for Glances (a0d7b954_glances)
23-03-26 12:03:07 WARNING (MainThread) [supervisor.addons.options] Unknown option 'bucket' for Glances (a0d7b954_glances)
23-03-26 12:03:07 WARNING (MainThread) [supervisor.addons.options] Unknown option 'org' for Glances (a0d7b954_glances)
23-03-26 12:08:11 WARNING (MainThread) [supervisor.addons.options] Unknown option 'version' for Glances (a0d7b954_glances)
23-03-26 12:08:11 WARNING (MainThread) [supervisor.addons.options] Unknown option 'token' for Glances (a0d7b954_glances)
23-03-26 12:08:11 WARNING (MainThread) [supervisor.addons.options] Unknown option 'bucket' for Glances (a0d7b954_glances)
23-03-26 12:08:11 WARNING (MainThread) [supervisor.addons.options] Unknown option 'org' for Glances (a0d7b954_glances)
23-03-26 12:13:15 WARNING (MainThread) [supervisor.addons.options] Unknown option 'version' for Glances (a0d7b954_glances)
23-03-26 12:13:15 WARNING (MainThread) [supervisor.addons.options] Unknown option 'token' for Glances (a0d7b954_glances)
23-03-26 12:13:15 WARNING (MainThread) [supervisor.addons.options] Unknown option 'bucket' for Glances (a0d7b954_glances)
23-03-26 12:13:15 WARNING (MainThread) [supervisor.addons.options] Unknown option 'org' for Glances (a0d7b954_glances)
23-03-26 12:18:18 WARNING (MainThread) [supervisor.addons.options] Unknown option 'version' for Glances (a0d7b954_glances)
23-03-26 12:18:18 WARNING (MainThread) [supervisor.addons.options] Unknown option 'token' for Glances (a0d7b954_glances)
23-03-26 12:18:18 WARNING (MainThread) [supervisor.addons.options] Unknown option 'bucket' for Glances (a0d7b954_glances)
23-03-26 12:18:18 WARNING (MainThread) [supervisor.addons.options] Unknown option 'org' for Glances (a0d7b954_glances)
```

how to fix the correct operation before upgrading to the current version Core 2023.3.6

**Comment by frenck** [comment] 2023-03-26 19:41
Duplicate of #325

**Closed by frenck** 2023-03-26 19:41 UTC
